/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsageIndexRouteImport } from './routes/usage/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChannelsIndexRouteImport } from './routes/channels/index'
import { Route as AutomationsIndexRouteImport } from './routes/automations/index'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as ChatSessionIdIndexRouteImport } from './routes/chat/$sessionId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageIndexRoute = UsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/settings/models',
  path: '/settings/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdIndexRoute = ChatSessionIdIndexRouteImport.update({
  id: '/chat/$sessionId/',
  path: '/chat/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/models': typeof SettingsModelsRoute
  '/automations/': typeof AutomationsIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/usage/': typeof UsageIndexRoute
  '/chat/$sessionId/': typeof ChatSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/models': typeof SettingsModelsRoute
  '/automations': typeof AutomationsIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/usage': typeof UsageIndexRoute
  '/chat/$sessionId': typeof ChatSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/models': typeof SettingsModelsRoute
  '/automations/': typeof AutomationsIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/usage/': typeof UsageIndexRoute
  '/chat/$sessionId/': typeof ChatSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/models'
    | '/automations/'
    | '/channels/'
    | '/chat/'
    | '/memory/'
    | '/settings/'
    | '/skills/'
    | '/usage/'
    | '/chat/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/models'
    | '/automations'
    | '/channels'
    | '/chat'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/chat/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/settings/models'
    | '/automations/'
    | '/channels/'
    | '/chat/'
    | '/memory/'
    | '/settings/'
    | '/skills/'
    | '/usage/'
    | '/chat/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  UsageIndexRoute: typeof UsageIndexRoute
  ChatSessionIdIndexRoute: typeof ChatSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage/': {
      id: '/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof UsageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/': {
      id: '/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/settings/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId/': {
      id: '/chat/$sessionId/'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId/'
      preLoaderRoute: typeof ChatSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  AutomationsIndexRoute: AutomationsIndexRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  UsageIndexRoute: UsageIndexRoute,
  ChatSessionIdIndexRoute: ChatSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
